#!/bin/bash
# derive_carrier.sh — Scaffold a custom carrier board DT overlay
# Part of imx95-bsp-skills
#
# Usage:
#   derive_carrier.sh --carrier-name <name> --base-dts <file> [options]
#
# Options:
#   --carrier-name <name>   Short slug for carrier (e.g. acme-carrier-v1)
#   --base-dts <file>       Base DTS filename (e.g. imx95-19x19-lpddr5-evk.dts)
#   --company <name>        Copyright holder (default: "Your Company")
#   --year <year>           Copyright year (default: current year)
#   --workspace <path>      BSP workspace root (default: auto-detect)
#   --dry-run               Print files without writing
#   -h, --help              Show this help

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

CARRIER_NAME=""
BASE_DTS="imx95-19x19-lpddr5-evk.dts"
COMPANY="Your Company"
YEAR="$(date +%Y)"
WORKSPACE=""
DRY_RUN=false

usage() {
    grep '^#' "$0" | grep -v '#!/' | sed 's/^# \{0,1\}//'
    exit 0
}

log()  { echo -e "${CYAN}[derive-carrier]${NC} $*"; }
ok()   { echo -e "${GREEN}[derive-carrier] ✓${NC} $*"; }
warn() { echo -e "${YELLOW}[derive-carrier] ⚠${NC} $*"; }
err()  { echo -e "${RED}[derive-carrier] ✗${NC} $*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --carrier-name) CARRIER_NAME="$2"; shift 2 ;;
        --base-dts)     BASE_DTS="$2";     shift 2 ;;
        --company)      COMPANY="$2";      shift 2 ;;
        --year)         YEAR="$2";         shift 2 ;;
        --workspace)    WORKSPACE="$2";    shift 2 ;;
        --dry-run)      DRY_RUN=true;      shift   ;;
        -h|--help)      usage ;;
        *) err "Unknown argument: $1" ;;
    esac
done

[[ -n "$CARRIER_NAME" ]] || err "--carrier-name is required"

# Sanitize carrier name: lowercase, replace spaces/underscores with hyphens
CARRIER_NAME="$(echo "$CARRIER_NAME" | tr '[:upper:]' '[:lower:]' | tr ' _' '-')"

# ── Locate workspace ──────────────────────────────────────────────────────────
find_workspace() {
    if [[ -n "$WORKSPACE" ]]; then echo "$WORKSPACE"; return; fi
    local dir="$PWD"
    while [[ "$dir" != "/" ]]; do
        [[ -f "$dir/targets/active_target.yaml" ]] && { echo "$dir"; return; }
        dir="$(dirname "$dir")"
    done
    echo "$PWD"
}

WORKSPACE="$(find_workspace)"
WORKSPACE="${WORKSPACE/#\~/$HOME}"

# ── Read active target ────────────────────────────────────────────────────────
ACTIVE_TARGET="$WORKSPACE/targets/active_target.yaml"
read_yaml() {
    local field="$1" default="${2:-}"
    [[ -f "$ACTIVE_TARGET" ]] || { echo "$default"; return; }
    python3 -c "
import sys, re
with open('$ACTIVE_TARGET') as f:
    for line in f:
        m = re.match(r'\s*${field}\s*:\s*[\"\'](.*)[\"\']\s*$', line)
        if m: print(m.group(1)); sys.exit(0)
        m = re.match(r'\s*${field}\s*:\s*(.*)\s*$', line)
        if m:
            v = m.group(1).strip().strip('\"\'')
            if v and v != 'null': print(v); sys.exit(0)
print('${default}')
" 2>/dev/null || echo "$default"
}

CUSTOM_LAYER_REL="$(read_yaml custom_layer sources/meta-imx95-custom)"
DT_OVERLAY_REL="$(read_yaml dt_overlay_dir sources/meta-imx95-custom/recipes-kernel/linux/files/overlays)"
PROFILE_NAME="$(read_yaml profile_name unknown)"

OVERLAY_DIR="$WORKSPACE/$DT_OVERLAY_REL"
BBAPPEND="$WORKSPACE/$CUSTOM_LAYER_REL/recipes-kernel/linux/linux-imx_%.bbappend"

MAIN_OVERLAY="$OVERLAY_DIR/imx95-${CARRIER_NAME}.dts"
PINMUX_OVERLAY="$OVERLAY_DIR/imx95-${CARRIER_NAME}-pinmux.dts"

log "=== imx95-derive-carrier ==="
log "Carrier name : $CARRIER_NAME"
log "Base DTS     : $BASE_DTS"
log "Company      : $COMPANY"
log "Overlay dir  : $OVERLAY_DIR"
echo ""

# ── Generate main overlay ─────────────────────────────────────────────────────
generate_main_overlay() {
    cat << DTS
// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright (C) ${YEAR} ${COMPANY}
 * Custom carrier board overlay for NXP i.MX 95
 * Base: ${BASE_DTS}
 *
 * Generated by imx95-bsp-skills / imx95-derive-carrier
 * Profile: ${PROFILE_NAME}
 *
 * IMPORTANT: Do not modify the base DTS (${BASE_DTS}) directly.
 * All carrier-specific changes belong in this overlay file or
 * in the sub-overlays included below.
 */

/dts-v1/;
/plugin/;

#include <dt-bindings/gpio/gpio.h>
#include <dt-bindings/clock/imx95-clock.h>
#include <dt-bindings/interrupt-controller/arm-gic.h>

/* Include pinmux sub-overlay */
#include "imx95-${CARRIER_NAME}-pinmux.dts"

/ {
    model = "NXP i.MX95 ${CARRIER_NAME} Carrier Board";
    compatible = "nxp,imx95-${CARRIER_NAME}", "nxp,imx95";

    /* ── Carrier-specific fixed regulators ─────────────────────────────── */
    /* Example: 3.3V fixed regulator for carrier peripherals
    reg_carrier_3v3: regulator-carrier-3v3 {
        compatible = "regulator-fixed";
        regulator-name = "carrier-3v3";
        regulator-min-microvolt = <3300000>;
        regulator-max-microvolt = <3300000>;
        regulator-always-on;
    };
    */
};

/* ── Carrier-specific node overrides ─────────────────────────────────────── */
/*
 * Add &node { ... }; overrides below as hardware is configured.
 * Use the following skills for guided configuration:
 *   imx95-customize-pinmux   — IOMUX/pinmux configuration
 *   imx95-customize-usb      — USB3 OTG / USB2 host
 *   imx95-customize-camera   — MIPI-CSI camera pipeline
 *   imx95-customize-clocks   — Clock assignments
 *   imx95-optimize-memory    — CMA / DMA-BUF pool tuning
 */

/* Example: disable a FRDM-specific peripheral not present on this carrier
&lpuart2 {
    status = "disabled";
};
*/
DTS
}

# ── Generate pinmux sub-overlay ───────────────────────────────────────────────
generate_pinmux_overlay() {
    cat << DTS
// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright (C) ${YEAR} ${COMPANY}
 * Pinmux sub-overlay for imx95-${CARRIER_NAME} carrier board
 *
 * Generated by imx95-bsp-skills / imx95-derive-carrier
 *
 * IOMUX reference: references/bsp-customization-iomux-dt.md
 * Pad naming: MX95_PAD_<PAD_NAME>__<FUNCTION>
 * PAD_CTL encoding: see references/bsp-customization-iomux-dt.md
 *
 * Use imx95-customize-pinmux skill to add pin groups.
 */

/dts-v1/;
/plugin/;

#include <dt-bindings/pinctrl/pins-imx95.h>

/* ── IOMUX pin group definitions ─────────────────────────────────────────── */
/*
 * Add pinctrl groups here. Example:
 *
 * &iomuxc {
 *     pinctrl_uart4: uart4grp {
 *         fsl,pins = <
 *             MX95_PAD_GPIO_IO04__LPUART4_TX    0x31e
 *             MX95_PAD_GPIO_IO05__LPUART4_RX    0x31e
 *         >;
 *     };
 * };
 *
 * Then assign to the peripheral:
 * &lpuart4 {
 *     pinctrl-names = "default";
 *     pinctrl-0 = <&pinctrl_uart4>;
 *     status = "okay";
 * };
 */
DTS
}

# ── Print or write files ──────────────────────────────────────────────────────
MAIN_CONTENT="$(generate_main_overlay)"
PINMUX_CONTENT="$(generate_pinmux_overlay)"

if [[ "$DRY_RUN" == "true" ]]; then
    echo "=== DRY RUN: imx95-${CARRIER_NAME}.dts ==="
    echo "$MAIN_CONTENT"
    echo ""
    echo "=== DRY RUN: imx95-${CARRIER_NAME}-pinmux.dts ==="
    echo "$PINMUX_CONTENT"
    echo ""
    log "Dry run complete — no files written."
    exit 0
fi

# Create overlay directory
mkdir -p "$OVERLAY_DIR"

# Write main overlay
echo "$MAIN_CONTENT" > "$MAIN_OVERLAY"
ok "Created: $MAIN_OVERLAY"

# Write pinmux overlay
echo "$PINMUX_CONTENT" > "$PINMUX_OVERLAY"
ok "Created: $PINMUX_OVERLAY"

# ── Update bbappend ───────────────────────────────────────────────────────────
if [[ -f "$BBAPPEND" ]]; then
    # Add SRC_URI entries if not already present
    if ! grep -q "imx95-${CARRIER_NAME}.dts" "$BBAPPEND"; then
        cat >> "$BBAPPEND" << BBAPP

# Carrier overlay: imx95-${CARRIER_NAME}
# Added by imx95-derive-carrier
SRC_URI += "file://overlays/imx95-${CARRIER_NAME}.dts"
SRC_URI += "file://overlays/imx95-${CARRIER_NAME}-pinmux.dts"
BBAPP
        ok "Updated bbappend: $BBAPPEND"
    else
        ok "bbappend already contains imx95-${CARRIER_NAME} entries"
    fi
else
    warn "bbappend not found at $BBAPPEND — create it with imx95-init-source"
fi

echo ""
ok "=== derive-carrier complete ==="
echo ""
echo "Files created:"
echo "  $MAIN_OVERLAY"
echo "  $PINMUX_OVERLAY"
echo ""
echo "Next steps:"
echo "  1. Review the generated files (shown above)"
echo "  2. Commit to overlay-tracker (commit-gate will be shown)"
echo "  3. Run imx95-customize-pinmux to configure IOMUX"
echo "  4. Run imx95-customize-usb, imx95-customize-camera, etc. as needed"
